[help_config]
Formato [elenco_posts]:
	<post_id>::<post_author>::<post_date>::<post_status>
 	<post_id>	: numero incrementale che identifica il post all'interno del topic
	<post_caption>	: titolo del post
	<post_status>	: stato del post:
			  visible	: il post e' visibile
			  censored	: il topic e' censurato
			  hidden	: il topic e' invisibile
Formato [post_text_X]:
E' il testo del post, puo' essere su piu' righe, nessuna delle quali vuote

[elenco_posts]
0::Michaelem::27/05/2013 21.11.58::visible
1::Michaelem::27/05/2013 21.22.15::visible
2::Michaelem::27/05/2013 21.24.10::visible
3::Michaelem::27/05/2013 21.27.51::visible
4::Michaelem::04/06/2013 21.52.10::visible
5::Michaelem::04/06/2013 21.54.05::visible
6::Michaelem::04/06/2013 21.55.49::visible
7::Michaelem::04/06/2013 21.57.52::visible
8::Michaelem::04/06/2013 21.58.58::visible
9::Michaelem::04/06/2013 22.00.21::visible
10::Michaelem::04/06/2013 22.02.00::visible
11::Michaelem::04/06/2013 22.03.58::visible
12::Michaelem::16/07/2013 21.41.49::visible
13::Michaelem::16/07/2013 21.46.26::visible
14::Michaelem::16/07/2013 21.48.13::visible
15::Michaelem::16/07/2013 21.51.14::visible
16::Michaelem::16/07/2013 21.53.28::visible
17::Michaelem::16/07/2013 21.55.48::visible
18::Michaelem::16/07/2013 21.57.33::visible
19::Michaelem::16/07/2013 21.59.00::visible
20::Michaelem::16/07/2013 22.00.42::visible
21::Michaelem::16/07/2013 22.02.13::visible
22::Michaelem::16/07/2013 22.03.25::visible
23::Michaelem::16/07/2013 22.04.43::visible
24::Michaelem::16/07/2013 22.06.13::visible
25::Michaelem::16/07/2013 22.06.58::visible
26::Michaelem::15/09/2013 11.35.02::visible
27::Michaelem::15/09/2013 11.36.44::visible
28::Michaelem::15/09/2013 11.38.14::visible
29::Michaelem::15/09/2013 11.39.52::visible
30::Michaelem::15/09/2013 11.41.15::visible
31::Michaelem::15/09/2013 11.42.35::visible
32::Michaelem::15/09/2013 11.43.57::visible
33::Michaelem::15/09/2013 11.46.27::visible
34::Michaelem::15/09/2013 11.49.15::visible
35::Michaelem::15/09/2013 11.51.48::visible

[post_text_0]
Dalla necropoli di Cerveteri si sollevò un trambusto di "già morti" quando Quasimodo il giardiniere fracasso il vaso di Pindaro...
"oh maledetto!" lo sbeffeggio Pericle la mummia... 'che dunque ramingo tu facesti?...
&nbsp;

[post_text_1]
"Datele il massaggio", urlò l'eretico...
"Il messaggio", consigliò il pivello...
"Insomma, fate quel che potete", interruppe l'abate...
"magari mangiate un kebab", ripetè lo sguaiato

[post_text_2]
Dai bassifondi del quartiere dei droidi si sollevavano urla empatiche che annichilivano gli allarmi elettrici delle monoposto a gettoni...
La città era davvero cambiata dopo le ultime elezioni imperiali...

[post_text_3]
Sì lo so, lo so...
Lo dicevo io...
E chi lo diceva?
A chi lo dicevi?
Oh perbacco, ma allora lui diceva qualcosa, lo diceva a qualcuno, ma non si sa cosa, quando, come e perché...
Ma sì, insomma, lo si diceva...
Perdindirindina, però!

[post_text_4]
DonnAbbondio detto "'o Sfringuello della sera" ripeteva spesso... 'a scarcioffola s'ammonna 'na foglia 'a la vota... e così difiunava per giornate intere...

[post_text_5]
La massaggiatrice calva dette aditoa molte dicerie quando apparve in pubblico affiancata a Micerino il Torvo...
"Eppur si amano", esclamò in un boato la folla...

[post_text_6]
Dal profondo della Foresta Nera si sollevò una diatriba che sconvolse non poco Mister J...
Ma questi tucani del cavolo proprio a Felicetta la Testardadovevano rompere le uova nel nido?

[post_text_7]
Il saggio bengalese usava dire...
Prima di sparare alla beccaccia rassicurati che la polvere da sparo non sia bagnata...

[post_text_8]
Le vaghe sembianze di Saturno m'allibrarono l'aere fresca et salutare del Vallone e già s'apria innanzi a noi lo Canale...

[post_text_9]
Goffredo detto l'Usignuolo esaminando le intrusioni e le ferite inferte al Grande Verme ne concluse che mai aveva visto un'Invertebrato  fare più simpatia...

[post_text_10]
Oh fauci possenti oh limpide e languide acque del Silarisoh estremo canto dell'esule celtico... dicea padre Ignazio durante le sue prediche nella Cripta delle Lapidi...
a tutti soccorse il destino...

[post_text_11]
Padre Enzo detto il Malfattore o anche Gesù Bambino avea da poco deciso di ritirarsi a vita privata quando gli si presentò innanzi Genoveffa la Turgida...
Gioiello divino, pensò lui... ed ancora una volta el core trasalì...

[post_text_12]
Gastone l'Africano guardò per anni le lucciole accendersi e spegnersi tra fieno e violacciotte selvatiche...
le cercava per intere notti per poi sfiorarle e darle dei nomi fantasiosi...
Daisy la sua preferita...

[post_text_13]
Ditegli "Basta... masnadiero di un filibustiero...
Tu rapisci le nostre puledre per lussuria e flautulenza...
A che dunque è servito il sacrificio del toro di Achille?..."

[post_text_14]
Solito sonnacchiuto salir e scendere solitariamente sballottolato su scalinate senza scivolar...

[post_text_15]
Oh bastioni di Tares che tutto sapete che tutto volgete al meglio vogliate trasportare al vento queste erudite parole che tanto nacquero da acque limpide sì come lo sgorgoglire in sinuosi ruscelletti...

[post_text_16]
Dalle alte fronde dell'albero dei tabù si levò un grido che di animalesco avea poco...
I suffumigi i suffumigi blaterò lo sciamano...
ma nulla poté contro il destino...

[post_text_17]
Dai profondi abissi del mare Littorio alle ombrosità della Foresta Nera si innalzò un coro di nefandezze come mai prima d'ora...
Segno che il popolo era pronto a soverchiar li animi queti...

[post_text_18]
Vincent Banghok usava disseminare fiori e petali lungo il suo cammino fino al giorno in cui incontrò Rosalinda la Smunta...
E sbocciò l'amor profano...

[post_text_19]
E che dunque movisti le acque imperigliose et fragili soltanto per aver vezzo da le tue ancelle?
Oh sventurate le mani orribili...

[post_text_20]
Mi parvero d'improvviso le sembianze de lo losco figuro de l'aquilonia...
e mentre rigettavo le parvenze mi sobbalzò un'oscura voce...

[post_text_21]
Adombrai la famelica disinvoltura de la donzella quasi le fosse un refrigerio,
ma dopo cotanto assiepare m'accorsi la sua vanità..

[post_text_22]
La mano de Dios colpì con una violenza ed un'alterigia che di umano avea poco...
I pusillanimi non poterono che aspettare la loro fine...

[post_text_23]
"E questo è solo l'inizio", deprecò Mister Muscolo dopo l'agognato e succulento antipasto...
Ma a ben vedere era altra la sua libidine...

[post_text_24]
Certi giorni veniamo accartocciati come birilli su di una pista da bowling,
o come fish and chips ai bordi di Piccadilly Circus

[post_text_25]
Un singol dinaro non fecer l'opulenza...

[post_text_26]
Frescobaldo Frescobaldi detto il Frascone era alla ricerca di Jolanda Vinciguerra quando le si apparve innanzi...
Che beltade pensò lei...

[post_text_27]
Le sfingi di Cheope e Micerino ci guardavano dall'alto con sguardo altero e quasi di rimprovero...
Che siano presagio di gloria e di ricchezza, pensai sognando...

[post_text_28]
Felice Sciosciammocca sembrava aver raggiunto un buon equilibrio dopo lo sposalizio con Brigitta Boccoli...
Ma fuoco di paglia era...

[post_text_29]
Il fantasma formaggino continuava a sostenere che il bimbo nato deboluccio andrebbe curato e forgiato così da tramutarlo in un macigno...
Ma le cose eran più facili a dirsi che a farsi...

[post_text_30]
Il fantasma di Canterville amava dilettarsi di scenografia e violoncello alla greca...
Abbandonò tutto dopo aver conosciuto Costantina la Truculenta...

[post_text_31]
Un antico detto ungherese narra:
a litigare tra lupo e agnello il riccio ci perde la mela e pure la pelliccia...

[post_text_32]
Un vecchio detto di Ceylon dice:
se la tartaruga nuota a pancia in su c'è qualcosa che non va!

[post_text_33]
Era da poco passata la mezzanotte quando dal bosco di cerze di Don Frisondolo si levò un rumore cupo e tremebondo...
Suor Cataldina avea posto il plantare destro su di un riccio di campagna...
Ma che facea in loco a quell'ora?

[post_text_34]
Pappone primo, re del potente stato dei Papusci, decretò che tutte le ragazze ancora nubili dovessero innamorarsi di lui...
Tutte tranne Rachele la racchia...
Ella gli si rifiutò...

[post_text_35]
Parlare poco delle cose che si fanno...
Tanto delle cose che si vorrebbero fare...
Niente delle cose già fatte...
